# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.140.1
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317 # OTLP gRPC
      - 8888:8888 # Collector セルフテレメトリ
      - 1777:1777 # pprof (Go profiling)
    deploy:
      resources:
        limits:
          memory: 256M

  prometheus:
    image: prom/prometheus:v3.7.3
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686

  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # ログインを不要にする
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
